[target]
victim-samba ansible_host=10.10.10.105
victim-database ansible_host=10.10.10.103
victim-redis ansible_host=10.10.10.102
victim-amazin ansible_host=10.10.10.104
victim-ftp ansible_host=10.10.10.101
victim1 ansible_host=10.10.10.106
victim2 ansible_host=10.10.10.107
victim3 ansible_host=10.10.10.108
victim4 ansible_host=10.10.10.109


# =============================================================================
# VARIABLES FOR ALL SERVERS
# =============================================================================
# These settings apply to every server in the inventory

[target:vars]
# The username and password to connect with
ansible_user=lwilsone
ansible_password=RedTeamrules123

# Use password authentication (disable SSH key requirement)
ansible_ssh_pass={{ ansible_password }}

# Tell Ansible where Python is on the remote servers
ansible_python_interpreter=/usr/bin/python3

# Connect through the CyberRange jump host
#ansible_ssh_common_args=-o ProxyJump=sshjump@ssh.cyberrange.rit.edu -o StrictHostKeyChecking=no