---
- name: Deploy All Persistence Mechanisms
  hosts: targets
  gather_facts: yes
  become: yes

  tasks:
    - name: Run all persistence playbooks
      include_playbook: "{{ item }}"
      loop:
        - cron_persistence.yml
        - systemd_timer_persistence.yml
        - systemd_service_persistence.yml
        - shell_profile_persistence.yml
        - service_misconfig_persistence.yml