[targets]
10.10.10.101 ansible_user=cyberrange ansible_ssh_pass=cyber123
10.10.10.102 ansible_user=cyberrange ansible_ssh_pass=cyber123
10.10.10.103 ansible_user=cyberrange ansible_ssh_pass=cyber123
10.10.10.104 ansible_user=cyberrange ansible_ssh_pass=cyber123
10.10.10.105 ansible_user=cyberrange ansible_ssh_pass=cyber123
10.10.10.106 ansible_user=cyberrange ansible_ssh_pass=cyber123
10.10.10.107 ansible_user=cyberrange ansible_ssh_pass=cyber123
10.10.10.108 ansible_user=cyberrange ansible_ssh_pass=cyber123
10.10.10.109 ansible_user=cyberrange ansible_ssh_pass=cyber123


[targets:vars]
ansible_python_interpreter=/usr/bin/python3