[target]
; victim-samba ansible_host=100.65.3.17
; victim-database ansible_host=100.65.4.179
; victim-redis ansible_host=100.65.2.100
; victim-amazin ansible_host=100.65.6.229
; victim-ftp ansible_host=100.65.8.4
; victim1 ansible_host=100.65.3.192
; victim2 ansible_host=100.65.2.156
; victim3 ansible_host=100.65.7.34
; victim4 ansible_host=100.65.8.205
victim1 ansible_host=100.65.3.240
victim2 ansible_host=100.65.2.160


# =============================================================================
# VARIABLES FOR ALL SERVERS
# =============================================================================
# These settings apply to every server in the inventory

[target:vars]
# The username and password to connect with
ansible_user=cyberrange
ansible_password=Cyberrange123!

# Use password authentication (disable SSH key requirement)
ansible_ssh_pass={{ ansible_password }}

# Tell Ansible where Python is on the remote servers
ansible_python_interpreter=/usr/bin/python3

# Connect through the CyberRange jump host
ansible_ssh_common_args=-o ProxyJump=sshjump@ssh.cyberrange.rit.edu -o StrictHostKeyChecking=no